# Site settings
title: Ligens Parallèles
email: fernando @ zarur.com.br
url: https://fzarur.github.io
description: "Collection of black and white photos about people and trains"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Fernando Zarur

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/fzarur
  - title: flickr
    url: https://flickr.com/fernandozarur

# Build settings
markdown: kramdown
permalink: pretty
